language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7
dist: xenial
sudo: true
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: LUXROBO
  password:
    secure: ebvlI2V0ikcsUtz5m1lMIOOHWoakJPsZLQTFy5qYFRR9Wi9mgnb3jKeFUt7TrnbWpD6/5foA+5/mAIdCsDPYD/Tg29KwgNi3QcDEYy/0AO0dAY/968ANKIAkNvF7oh81BTLOkza2RkWubtezRUIYE352p+77FQoasH8vQdaa1OvOu+tGW3gUj1iGYZf6ZgmwLmTKZx+i3faP/brvGF/7foUt1dErJx8GunEMBXZB1Fpuz/wcUqU5LmhsyCEuNxyRywH9q2tD8OLupOs+SJ85u5dTrrLTV1AbwfTL1JWPGvzVS30ibyYTBnQqaJQVtndfP/68CWuqKD5qXKcrbTYeAoyHFtouC5jpGJxxWOBK71yq+hgGJ5sFwlUpLBl4n87hBd6OLKyBcb69FWkIjmwbLjYuStRWLpk8GofP9Qv4s4JL95hyNLps+XkpKyH+rRhuZl7NF7BfAREj3ChsZJmKteTxajOywIO3lkDxHZOGdsyKRzCAcU6B77MKgCqeIj/OPzfIPo1jES2uDikq1ZCjhV1j3lfSsDtGFiXPSci1/ROdKJT72U72gZ1CNxBoAwYimoWvme0UgO5j46+gsmzjUvz6z+OSGBII1tF6NEEtXI5X0cIxaah/01mXw/hjfg5efUOQfPRRQ4jsKtzWvZONCAnAJlM3LelKsO1fVo1nFAQ=
  on:
    tags: true
    repo: LUXROBO/MODI-Python-API
    python: 3.7
notifications:
  slack:
    secure: J3mKtnO2ChS3XGenXoLvPXeTPsr+q34ms9GAetkMRMtV3AhGCg4C4Ir/01BYZdr4kOFQ63Vw1Ru8gjSsvnlQPltunVG+1ZNTYpea6V84PJ1GZyAFWEESSsXKhBYiD1OArF+EHRtgwyAS7VhgD/FM6ojjlf1AKW1oz6Rm7kBmM9/U7Xm+4NQHTgPBd44NO5VKFqZ3lnC+jiZz1Wi4gZg2nHgcwnoUH7kCI4GUcZ0zEzGdriLv3dpeRw4QJJ/X+wHH4thbqILrR0I94Nl5XjdmX0uqZsok3lKo2qwCA9GrJlmhsM9kH1NXWm2yba6bYa4+6b720e+wwp0hlaCOd+plXzG9EEBg/CjEQXQQA8tg9b3E7CKr/FlGRCOK1Rv4k+r/X3L+LmAxVP/VgnphCeE7sU3elftLkayCXidowFFFi9xda0g9WZetXPsHXhwblqAnVfS+GuzqHjvF/kHi/Mk+Va9RLt94X5T4cOYCEewTzY0HAVsIVdvr5X0oQIPKhjHl+sIVTg8giIaziFQECOKyLdTUx8/UycTxGAesFFo0qphTcwlXGe9/rvjazC1GILBGrec/5H4sEnLbDE/RR/Kl9W4/PXagKZBwN0W0qxnLTWYXVvWuhbwcagz981gLSeqao60iFaZ0KfX0aggk1itu4DTQe2Dqei9+BU6sq5GaH0Y=
