language: python

jobs:
  include:
    - name: "Python convention test"
      env: TOXENV=flake8

    - name: "Python 3.8 on Linux"
      python: 3.8
      env: TOXENV=linux-py38
    - name: "Python 3.7 on Linux"
      python: 3.7
      env: TOXENV=linux-py37
    - name: "Python 3.6 on Linux"
      python: 3.6
      env: TOXENV=linux-py36

    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install:
          pyenv local 3.8-dev
      python: 3.8
      env: TOXENV=macos-py38
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.6
      language: shell
      python: 3.7
      env: TOXENV=macos-py37
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11.6
      before_install:
          - pyenv update
          - pyenv install 3.6.0
      language: shell
      python: 3.6
      env: TOXENV=macos-py36

    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOXENV=windows-py38
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=windows-py37
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.1
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - TOXENV=windows-py36

install:
  - pip install tox-travis coveralls tox-pyenv

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: LUXROBO
  password:
    secure: ebvlI2V0ikcsUtz5m1lMIOOHWoakJPsZLQTFy5qYFRR9Wi9mgnb3jKeFUt7TrnbWpD6/5foA+5/mAIdCsDPYD/Tg29KwgNi3QcDEYy/0AO0dAY/968ANKIAkNvF7oh81BTLOkza2RkWubtezRUIYE352p+77FQoasH8vQdaa1OvOu+tGW3gUj1iGYZf6ZgmwLmTKZx+i3faP/brvGF/7foUt1dErJx8GunEMBXZB1Fpuz/wcUqU5LmhsyCEuNxyRywH9q2tD8OLupOs+SJ85u5dTrrLTV1AbwfTL1JWPGvzVS30ibyYTBnQqaJQVtndfP/68CWuqKD5qXKcrbTYeAoyHFtouC5jpGJxxWOBK71yq+hgGJ5sFwlUpLBl4n87hBd6OLKyBcb69FWkIjmwbLjYuStRWLpk8GofP9Qv4s4JL95hyNLps+XkpKyH+rRhuZl7NF7BfAREj3ChsZJmKteTxajOywIO3lkDxHZOGdsyKRzCAcU6B77MKgCqeIj/OPzfIPo1jES2uDikq1ZCjhV1j3lfSsDtGFiXPSci1/ROdKJT72U72gZ1CNxBoAwYimoWvme0UgO5j46+gsmzjUvz6z+OSGBII1tF6NEEtXI5X0cIxaah/01mXw/hjfg5efUOQfPRRQ4jsKtzWvZONCAnAJlM3LelKsO1fVo1nFAQ=
  distributions: sdist bdist_wheel
  on:
    repo: LUXROBO/pymodi
    branch: develop
    tags: true
    python: 3.6
