
name: Convention Test (Flake8)

on: pull_request

jobs:
  # Runs convention test
  convention:
    name: Convention Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-annotations
        pip install flake8-docstrings
        pip install flake8-rst-docstrings
        pip install -r requirements.txt
    - name: Flake8 convention test
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 modi tests --ignore=R,D,A,W503 --count --statistics
    - name: Flake8 type annotation check
      run: flake8 modi tests --select=A --count --statistics --exit-zero
    - name: Flake8 docstring check
      run: flake8 modi tests --select=D102,D103,D105,R --count --statistics --exit-zero
