# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deployment (PyPI)

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bumpversion
    - name: Checkout release branch
      run: |
        git config --local user.email ${{ secrets.GH_MAIL }}
        git config --local user.name ${{ secrets.GH_USER }}
        NEW_VERSION=$(git describe --tags | cut -d - -f 1 | cut -c2-)
        CURR_VERSION=$(cat setup.cfg | grep 'current_version = ' | cut -d '=' -f 2 | cut -c 2-6)
        if [[ $(echo $NEW_VERSION | cut -d '.' -f 1 ) != $(echo $CURR_VERSION | cut -d '.' -f 1) ]]; then bumpversion major;
        elif [[ $(echo $NEW_VERSION | cut -d '.' -f 2 ) != $(echo $CURR_VERSION | cut -d '.' -f 2) ]]; then bumpversion minor;
        elif [[ $(echo $NEW_VERSION | cut -d '.' -f 3 ) != $(echo $CURR_VERSION | cut -d '.' -f 3) ]]; then bumpversion patch;
        fi
        BRANCH_NAME="release/$NEW_VERSION"
        echo $BRANCH_NAME
        echo "::set-output name=new_branch::$BRANCH_NAME"
        git checkout -b $BRANCH_NAME
        git push --set-upstream origin $BRANCH_NAME
      id: checkout_branch
    - name: Create a pull request to master branch
      uses: repo-sync/pull-request@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: ${{ steps.checkout_branch.outputs.new_branch }}
        pr_title: "Merge new release"
    - name: Create a pull request to master branch
      uses: repo-sync/pull-request@master
      with:
        destination_branch: "develop"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: ${{ steps.checkout_branch.outputs.new_branch }}
        pr_title: "Merge new release"
    - name: Build and publish
      env:
        TWINE_USERNAME: $
        {{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
    - name: Send email
      uses: dawidd6/action-send-mail@v2.2.0
      with:
        server_address: smtp-mail.outlook.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: A new version of PyMODI is successfully released!
        body: file://HISTORY.md
        to: tech@luxrobo.com
        from: PyMODI
    - name: Microsoft Teams Notification
      uses: jdcargile/ms-teams-notification@v1.2
      with:
        # GitHub Token
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Microsoft Teams Webhook URI
        ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
        # Message to be sent to Microsoft Teams channel
        notification-summary: A new version of PyMODI is released!!
        # Color of notification header line
        notification-color: 17a2b8
        # Timezone (ex. America/Denver)
        timezone: Korea/Seoul
